config/routes.rb
Rails.application.routes.draw do

  root 'chatroom#index'
  get 'login', to: 'sessions#new'
  get 'sign-up', to: 'user_registrations#sign_up'
  post 'create-user', to: 'user_registrations#create_user'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord

  validates :body, presence: true
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord

  validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP }
  has_secure_password
  has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/chatroom_controller.rb
class ChatroomController < ApplicationController
  def index
    @messages = Message.all
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
end

app/controllers/user_registrations_controller.rb
class UserRegistrationsController < ApplicationController

  def create_user
    puts 'request hit'
  end

  def sign_up

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chatroom_helper.rb
module ChatroomHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_registrations_helper.rb
module UserRegistrationsHelper
end

app/views/chatroom/index.html.erb
<h2 class="ui center aligned medium icon header">
  <i class="circular orange users icon"></i>
  Hey, We are here to communicate
</h2>

<div class="ui two column grid" style="padding-top: 50px">
  <div class="twelve wide column">
    <div class="ui fluid raised card chatBox">
      <div class="content">
        <div class="ui feed">
          <%= render @messages %>
        </div>
      </div>
      <div class="extra content">
        <form class="ui reply form">
          <div class="field">
            <div class="ui fluid icon input">
              <input type="text" placeholder="Enter message...">
              <i class="bordered inverted orange icon edit"></i>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
  <div class="four wide column">
    <div class="ui fluid raised card chatBox">
      <div class="content">
        <div class="ui inverted vertical menu">
          <a class="active item">
            Home
          </a>
          <a class="item">
            Messages
          </a>
          <a class="item">
            Friends
          </a>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<%= link_to 'Chatroom', root_path, class: 'item' %>
<a class="item">
  Messages
</a>
<div class="right menu">
  <div class="ui dropdown item">
    Account <i class="dropdown icon"></i>
    <div class="menu">
      <a class="item">Log out</a>
      <%= link_to 'Log in', login_path, class: 'item' %>
    </div>
  </div>
  <div class="item">
    <%= link_to 'Sign Up', sign_up_path, class: "ui primary button" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Messaging</title>
  <%= favicon_link_tag %>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<div class="ui large inverted menu">
  <div class="ui container">
    <%= render 'layouts/navigation' %>
  </div>
</div>
<div class="ui container">
  <%= yield %>
</div>
</body>
</html>

app/views/messages/_message.html.erb
<div class="event">
  <div class="content">
    <div class="summary">
      <em><%= message.user.email %></em> => <%= message.body %>
    </div>
  </div>
</div>

app/views/user_registrations/sign_up.html.erb
<div class="ui placeholder segment">
  <div class="ui very relaxed stackable grid">
    <div class="column">
      <div class="ui form">
        <div class="ui grid">
          <div class="field eight wide column">
            <label>Name</label>
            <div class="ui left icon input">
              <input type="text" placeholder="Enter name">
              <i class="user icon"></i>
            </div>
          </div>
          <div class="field eight wide column">
            <label>Email</label>
            <div class="ui left icon input">
              <input type="email" placeholder="Enter email">
              <i class="user icon"></i>
            </div>
          </div>
        </div>
        <div class="ui grid">
          <div class="field eight wide column">
            <label>Mobile Number</label>
            <div class="ui left icon input">
              <input type="text" placeholder="Enter mobile number">
              <i class="user icon"></i>
            </div>
          </div>
          <div class="field eight wide column">
            <label>Password</label>
            <div class="ui left icon input">
              <input type="password" placeholder="Enter password">
              <i class="lock icon"></i>
            </div>
          </div>
        </div>
        <div class="ui blue submit button">Sign Up</div>
      </div>
    </div>
  </div>
</div>